enable_disqus: false
enable_analytics: false
highlighter: rouge
permalink: pretty

#_url: http://localhost:4000
#_url: https://flaviomicheletti.github.io/logica-de-programacao
_url: http://www.devfuria.com.br/logica-de-programacao

secao: logica-de-programacao

defaults:
  -
    scope:
      path: ""
    values:
      layout: "artigo"
